/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_content_delivery_bucket": "bsp-kalyan-dev",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "https://djxxhmaart7ya.cloudfront.net",
    "aws_appsync_graphqlEndpoint": "https://s2innuyymfambjqxnzppxhntgq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-w7j5czbzg5aqxlcfyrl55y6lgi",
    "aws_cognito_identity_pool_id": "ap-south-1:1430ebba-79c9-47c6-bfba-f1a8d4c22223",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_4AQziL2h3",
    "aws_user_pools_web_client_id": "5ofqj6glc28rr0tk76khs4s3h3",
    "oauth": {}
};


export default awsmobile;
